---
title: "Stat 432 Homework 2 Solution"
date: "Assigned: Aug 29, 2022; <span style='color:red'>Due: 11:59 PM CT, Sep 15, 2022</span>"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
    toc_depth: 2
---

<style>
body {
text-align: justify}
</style>

```{css, echo=FALSE}
.solution {
background-color: #CCDDFF;
}
```

## Instruction

```{r}
library("tidyverse")
spaceship = read.csv("spaceshiptrain.csv")
spaceship = as_tibble(spaceship)

spaceship_test = read.csv("spaceshiptest.csv")
spaceship_test = as_tibble(spaceship_test)
```
```{r}
library("tidyverse")
# removing useless variables
# we should parse passenger_Id into group, since the id by itself is useless, but data about the group metadata might be useful(size of group they're in?)

# get_group_size =
split_passenger_id = function(spaceship) {
  
}

remove_cols = function(spaceship, names) {
  spaceship = spaceship %>% 
    select(-one_of(names)) %>% drop_na
}


```  
```{r}
# split up passengerID(ex ->"1234-01") into group_id ("1234") and pers_id ("01). Also splits up cabin(ex-> "F/226/P") int Deck("F"), Num(226) and Side("P")
split_passenger_and_cabin = function(spaceship) {
  spaceship = spaceship %>% 
  mutate(
    Group_id = strtoi(substr(PassengerId, 1, 4), base=10L),
    Pers_id = strtoi(substr(PassengerId, 6, 7), base=10L),
    Deck = substr(Cabin, 1, 1),
    Num = as.numeric(str_sub(Cabin, 3, -3)),
    Side = str_sub(Cabin, -1, -1)
  ) %>%
  remove_cols(c("PassengerId", "Cabin", "Name"))
  spaceship
}

spaceship_2 = spaceship %>% split_passenger_and_cabin


``` 
```{r}
# find size of group that each person is traveling in
add_group_size = function(spaceship) {
  spaceship = spaceship %>% 
  group_by(Group_id) %>%
  mutate(
    Group_size = max(Pers_id)
  )
  spaceship %>%
  ungroup() %>%
  remove_cols(c("Pers_id"))
}

```
```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
# sets null planet values to most commmon planet in group
handle_null_planet = function(spaceship) {
  spaceship = spaceship %>% 
  group_by(Group_id) %>%
  mutate(
    HomePlanet = ifelse(HomePlanet == "", NA, HomePlanet),
    Destination = ifelse(Destination == "", NA, Destination),
    Deck = ifelse(Deck == "", NA, Deck)
  ) %>%
  mutate(
    HomePlanet = replace_na(HomePlanet, getmode(HomePlanet)),
    Destination = replace_na(Destination, getmode(Destination)),
    Deck = replace_na(Deck, getmode(Deck))
  ) %>%
  ungroup()
  
}
```
```{r}

handle_cryo_sleep = function(spaceship) {
  # spaceship = spaceship %>% 
  #   mutate(
  #     Spa = ifelse(is.na(Spa) & CryoSleep == TRUE, 0, Spa),
  #     FoodCourt = ifelse(is.na(FoodCourt) & CryoSleep == TRUE, 0, FoodCourt),
  #   )
  # spaceship
  spaceship = spaceship %>%
    mutate(
         RoomService = ifelse(is.na(RoomService) & CryoSleep == "True", 0, RoomService),
         FoodCourt = ifelse(is.na(FoodCourt) & CryoSleep == "True", 0, FoodCourt),
         ShoppingMall = ifelse(is.na(ShoppingMall) & CryoSleep == "True", 0, ShoppingMall),
         Spa = ifelse(is.na(Spa & CryoSleep == "True"), 0, Spa),
         VRDeck = ifelse(is.na(VRDeck) & CryoSleep == "True", 0, VRDeck)
         )
}

spaceship_2 = spaceship %>% 
  handle_cryo_sleep

na_prop = function(vec){
  sum(is.na(vec)) / length(vec)
}

```
```{r}
# Fill in Nulls with Mode
fill_nulls_with_mode = function(spaceship) {
  spaceship %>%
  ungroup() %>%
  mutate(
    HomePlanet = ifelse(HomePlanet == "", NA, HomePlanet),
    Destination = ifelse(Destination == "", NA, Destination),
    Deck = ifelse(Deck == "", NA, Deck),
    Side = ifelse(Side == "", NA, Side),
    CryoSleep = ifelse(CryoSleep == "", NA, CryoSleep),
    VIP = ifelse(VIP == "", NA, VIP)
    
  ) %>%
  mutate(
    HomePlanet = replace_na(HomePlanet, getmode(HomePlanet)),
    Destination = replace_na(Destination, getmode(Destination)),
    Deck = replace_na(Deck, getmode(Deck)),
    Side = replace_na(Side, getmode(Side)),
    CryoSleep = replace_na(CryoSleep, getmode(CryoSleep)),
    VIP = replace_na(VIP, getmode(VIP))
  ) 
}
spaceship_2 = spaceship %>% 
  split_passenger_and_cabin %>% 
  handle_null_planet %>%
  fill_nulls_with_mode
```
```{r}
fill_age_with_lm = function(spaceship) {
  model = lm(Age ~ VIP + Group_size + HomePlanet + Destination + Deck, data = spaceship)
  # add predicted age instead of null values.
  spaceship_age_na = spaceship %>% filter(is.na(Age))
  spaceship$Age[is.na(spaceship$Age)] = predict(model, spaceship_age_na)
  spaceship
}

spaceship_2 = spaceship %>% 
  split_passenger_and_cabin %>% 
  add_group_size %>%
  handle_null_planet %>%
  fill_nulls_with_mode %>%
  fill_age_with_lm

```
```{r}
set.seed(101)
library(mice)
# use mice to fill in spending collumns
fill_in_spending_nulls_with_mice = function(spaceship) {
    spaceship_subset = spaceship %>% 
    select(RoomService, FoodCourt, ShoppingMall, Spa, VRDeck, VIP, Age, Side, Deck, Group_size)
    
    spending_mice =  mice(spaceship_subset, method = c(rep("pmm", 5), rep("", 5)), maxit = 20)
    
    # check which dataset you want to use
  #spending_mice$imp$RoomService
  
  # impute new data
  final_clean_amenity_df = complete(spending_mice, 1)
  
  # replace in full df
  print(head(final_clean_amenity_df[,1:5]))
  spaceship[,6:10] = final_clean_amenity_df[,1:5]
  spaceship
  
}
```
```{r}
# save processed data to csv file.
combine_spending_cols = function(spaceship) {
  spaceship %>% 
  mutate(
    LuxuryExpenses = RoomService + Spa + VRDeck,
    RegularExpenses = FoodCourt + ShoppingMall
  ) %>%
  remove_cols(c("RoomService", "ShoppingMall", "Spa", "VRDeck", "FoodCourt" ))
}
```
```{r}
# save processed data to csv file.
change_transported_to_binary = function(spaceship) {
  spaceship %>% 
  mutate(
    Transported = ifelse(Transported=="True",1,0)
  ) 
}
spaceship_2 = spaceship %>% change_transported_to_binary
```

```{r}
# save processed data to csv file.
process_data = function(spaceship) {
  spaceship %>% 
  split_passenger_and_cabin %>%
  add_group_size %>%
  handle_null_planet %>%
  handle_cryo_sleep %>%
  fill_nulls_with_mode %>%
  fill_age_with_lm %>%
  fill_in_spending_nulls_with_mice %>%
  combine_spending_cols %>%
  change_transported_to_binary
}
spaceship_processed = spaceship %>% process_data
  
write.csv(spaceship_processed, "spaceshiptrain_processed.csv", row.names= FALSE)

spaceship_test_processed = spaceship_test %>% process_data

write.csv(spaceship_test_processed, "spaceshiptest_processed.csv", row.names= FALSE)

```


```{r}


```
  
